#%RAML 1.0 ResourceType
  get:
    description: This api is used to fetch all the                        <<resourcePathName>>
    is : <<traitRef>>
    responses:
      200:
        body:
          application/json:
            example: <<exampleRef>>


  post:
    description: This api is used to add new tutorial.
    is : <<traitRef>>
    body:
      application/json:
        type : <<tutorialDtRef>>
    responses:
      201:
        body:
          application/json:
            example:
                  Message : <<resourcePathName>> added.
            